api_platform:
    title: 'Houry Tennessee Api'
    description: 'Api for Tennessee houry portfolio.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 100
