version: '3'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: 968543fa851d
    ports:
      - "8080:80"
    

volumes:
  my-db: